spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jimmer?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: root # 替换为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: 127128
  jpa:
    hibernate:
      ddl-auto: update # 添加这个可以让Hibernate自动创建/更新表结构
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080

# Jimmer特定配置
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true # 开发时显示SQL，生产环境建议关闭